version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    container_name: bootnode
    env_file:
      - .env
    image: geth-client:1.0.0
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    command:
      --nodekeyhex=${NODE_KEY}
      --nodiscover
      --ipcdisable
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:

  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    container_name: rpc-endpoint
    env_file:
      - .env
    image: geth-client:1.0.0
    depends_on:
      - geth-bootnode    
    command:
      --bootnodes="enode://${NODE_ID}@geth-bootnode:30303"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="*"
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    ports:
      - "${RPC_PORT}:8545"
    networks:
      priv-eth-net:

  geth-miner:
    hostname: geth-miner
    container_name: miner
    env_file:
      - .env
    image: geth-client:1.0.0
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://${NODE_ID}@geth-bootnode:30303"
      --mine
      --miner.threads=1
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28