version: "3"

services:
  geth:
    image: ethereum/client-go
    container_name: ethereum
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${NODE_PORT}:30303"
      - "${NODE_PORT}:30303/udp"
      - "${RPC_PORT}:8545"
      - "${WEBSOCKET_PORT}:8546"
    volumes:
      - ./chaindata:/root/.ethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: init /root/.ethereum/genesis.json
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
