version: '2'
services:
  init:
    image: ethereum/client-go
    container_name: ethereum-init
    command:
      --nodekeyhex=${NODE_KEY}
      --nodiscover
      --ipcdisable
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
      init /root/.ethereum/genesis.json
    volumes:
      - ./chaindata:/root/.ethereum

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28